# Generated by Django 3.2.5 on 2021-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
