# Generated by Django 3.2.5 on 2021-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='collection',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='collection',
            field=models.ManyToManyField(to='mysite.Collection'),
        ),
    ]
