# Generated by Django 3.2.5 on 2021-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(related_name='category_subcategory', to='mysite.Category'),
        ),
    ]
