# Generated by Django 3.2.5 on 2021-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='collection',
            field=models.ManyToManyField(related_name='collection_category', to='mysite.Collection'),
        ),
    ]
